/* Generated By:JavaCC: Do not edit this line. AlinousObjectParserTokenManager.java */
package org.alinous.parser.object;

public class AlinousObjectParserTokenManager implements AlinousObjectParserConstants
{
  public  java.io.PrintStream debugStream = System.out;
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private final int jjMoveStringLiteralDfa0_5()
{
   switch(curChar)
   {
      case 60:
         jjmatchedKind = 6;
         return jjMoveStringLiteralDfa1_5(0x80L);
      default :
         return 1;
   }
}
private final int jjMoveStringLiteralDfa1_5(long active0)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      return 1;
   }
   switch(curChar)
   {
      case 47:
         if ((active0 & 0x80L) != 0L)
            return jjStopAtPos(1, 7);
         break;
      default :
         return 2;
   }
   return 2;
}
private final int jjMoveStringLiteralDfa0_0()
{
   switch(curChar)
   {
      case 0:
         return jjStopAtPos(0, 111);
      case 60:
         jjmatchedKind = 109;
         return jjMoveStringLiteralDfa1_0(0x400000000000L);
      default :
         return 1;
   }
}
private final int jjMoveStringLiteralDfa1_0(long active1)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      return 1;
   }
   switch(curChar)
   {
      case 47:
         if ((active1 & 0x400000000000L) != 0L)
            return jjStopAtPos(1, 110);
         break;
      default :
         return 2;
   }
   return 2;
}
private final int jjMoveStringLiteralDfa0_1()
{
   switch(curChar)
   {
      case 39:
         return jjStopAtPos(0, 106);
      case 92:
         return jjMoveStringLiteralDfa1_1(0x80000000000L);
      default :
         return 1;
   }
}
private final int jjMoveStringLiteralDfa1_1(long active1)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      return 1;
   }
   switch(curChar)
   {
      case 39:
         if ((active1 & 0x80000000000L) != 0L)
            return jjStopAtPos(1, 107);
         break;
      default :
         return 2;
   }
   return 2;
}
private final int jjMoveStringLiteralDfa0_2()
{
   switch(curChar)
   {
      case 34:
         return jjStopAtPos(0, 103);
      case 92:
         return jjMoveStringLiteralDfa1_2(0x10000000000L);
      default :
         return 1;
   }
}
private final int jjMoveStringLiteralDfa1_2(long active1)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      return 1;
   }
   switch(curChar)
   {
      case 34:
         if ((active1 & 0x10000000000L) != 0L)
            return jjStopAtPos(1, 104);
         break;
      default :
         return 2;
   }
   return 2;
}
private final int jjMoveStringLiteralDfa0_4()
{
   switch(curChar)
   {
      case 9:
         jjmatchedKind = 10;
         return jjMoveNfa_4(0, 0);
      case 10:
         jjmatchedKind = 11;
         return jjMoveNfa_4(0, 0);
      case 13:
         jjmatchedKind = 12;
         return jjMoveNfa_4(0, 0);
      case 32:
         jjmatchedKind = 9;
         return jjMoveNfa_4(0, 0);
      case 33:
         return jjMoveStringLiteralDfa1_4(0x0L, 0x1002000000L);
      case 34:
         jjmatchedKind = 98;
         return jjMoveNfa_4(0, 0);
      case 39:
         jjmatchedKind = 99;
         return jjMoveNfa_4(0, 0);
      case 47:
         return jjMoveStringLiteralDfa1_4(0x0L, 0x200000000L);
      case 58:
         jjmatchedKind = 91;
         return jjMoveNfa_4(0, 0);
      case 61:
         jjmatchedKind = 90;
         return jjMoveNfa_4(0, 0);
      case 62:
         jjmatchedKind = 96;
         return jjMoveNfa_4(0, 0);
      case 63:
         jjmatchedKind = 95;
         return jjMoveNfa_4(0, 0);
      case 65:
         jjmatchedKind = 26;
         return jjMoveStringLiteralDfa1_4(0x8000000000000L, 0x803000L);
      case 66:
         jjmatchedKind = 19;
         return jjMoveStringLiteralDfa1_4(0x10150000108000L, 0x80000L);
      case 67:
         return jjMoveStringLiteralDfa1_4(0x1c0800000000000L, 0x140000L);
      case 68:
         return jjMoveStringLiteralDfa1_4(0x40000000L, 0xc00L);
      case 69:
         return jjMoveStringLiteralDfa1_4(0x400000000000000L, 0x0L);
      case 70:
         return jjMoveStringLiteralDfa1_4(0x18000040a0000000L, 0x0L);
      case 72:
         return jjMoveStringLiteralDfa1_4(0x1200000e02000L, 0x380L);
      case 73:
         jjmatchedKind = 70;
         return jjMoveStringLiteralDfa1_4(0x2000000102000000L, 0x0L);
      case 76:
         return jjMoveStringLiteralDfa1_4(0x202a000000000L, 0x0L);
      case 77:
         return jjMoveStringLiteralDfa1_4(0x8000000L, 0x20L);
      case 78:
         return jjMoveStringLiteralDfa1_4(0x10000000L, 0x0L);
      case 79:
         return jjMoveStringLiteralDfa1_4(0xc00000000L, 0x4010L);
      case 80:
         jjmatchedKind = 24;
         return jjMoveStringLiteralDfa1_4(0x220000000000000L, 0x0L);
      case 81:
         jjmatchedKind = 67;
         return jjMoveNfa_4(0, 0);
      case 83:
         return jjMoveStringLiteralDfa1_4(0x4004080200000000L, 0x1200003L);
      case 84:
         return jjMoveStringLiteralDfa1_4(0x8000401000074000L, 0x38000L);
      case 85:
         return jjMoveStringLiteralDfa1_4(0x0L, 0x400004L);
      case 97:
         jjmatchedKind = 26;
         return jjMoveStringLiteralDfa1_4(0x8000000000000L, 0x803000L);
      case 98:
         jjmatchedKind = 19;
         return jjMoveStringLiteralDfa1_4(0x10150000108000L, 0x80000L);
      case 99:
         return jjMoveStringLiteralDfa1_4(0x1c0800000000000L, 0x140000L);
      case 100:
         return jjMoveStringLiteralDfa1_4(0x40000000L, 0xc00L);
      case 101:
         return jjMoveStringLiteralDfa1_4(0x400000000000000L, 0x0L);
      case 102:
         return jjMoveStringLiteralDfa1_4(0x18000040a0000000L, 0x0L);
      case 104:
         return jjMoveStringLiteralDfa1_4(0x1200000e02000L, 0x380L);
      case 105:
         jjmatchedKind = 70;
         return jjMoveStringLiteralDfa1_4(0x2000000102000000L, 0x0L);
      case 108:
         return jjMoveStringLiteralDfa1_4(0x202a000000000L, 0x0L);
      case 109:
         return jjMoveStringLiteralDfa1_4(0x8000000L, 0x20L);
      case 110:
         return jjMoveStringLiteralDfa1_4(0x10000000L, 0x0L);
      case 111:
         return jjMoveStringLiteralDfa1_4(0xc00000000L, 0x4010L);
      case 112:
         jjmatchedKind = 24;
         return jjMoveStringLiteralDfa1_4(0x220000000000000L, 0x0L);
      case 113:
         jjmatchedKind = 67;
         return jjMoveNfa_4(0, 0);
      case 115:
         return jjMoveStringLiteralDfa1_4(0x4004080200000000L, 0x1200003L);
      case 116:
         return jjMoveStringLiteralDfa1_4(0x8000401000074000L, 0x38000L);
      case 117:
         return jjMoveStringLiteralDfa1_4(0x0L, 0x400004L);
      default :
         return jjMoveNfa_4(0, 0);
   }
}
private final int jjMoveStringLiteralDfa1_4(long active0, long active1)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_4(0, 0);
   }
   switch(curChar)
   {
      case 45:
         return jjMoveStringLiteralDfa2_4(active0, 0L, active1, 0x1000000000L);
      case 49:
         if ((active0 & 0x200000L) != 0L)
         {
            jjmatchedKind = 21;
            jjmatchedPos = 1;
         }
         break;
      case 50:
         if ((active0 & 0x400000L) != 0L)
         {
            jjmatchedKind = 22;
            jjmatchedPos = 1;
         }
         break;
      case 51:
         if ((active0 & 0x800000L) != 0L)
         {
            jjmatchedKind = 23;
            jjmatchedPos = 1;
         }
         break;
      case 52:
         if ((active1 & 0x80L) != 0L)
         {
            jjmatchedKind = 71;
            jjmatchedPos = 1;
         }
         break;
      case 53:
         if ((active1 & 0x100L) != 0L)
         {
            jjmatchedKind = 72;
            jjmatchedPos = 1;
         }
         break;
      case 54:
         if ((active1 & 0x200L) != 0L)
         {
            jjmatchedKind = 73;
            jjmatchedPos = 1;
         }
         break;
      case 62:
         if ((active1 & 0x200000000L) != 0L)
         {
            jjmatchedKind = 97;
            jjmatchedPos = 1;
         }
         break;
      case 65:
         return jjMoveStringLiteralDfa2_4(active0, 0xb0008000010000L, active1, 0x20L);
      case 66:
         return jjMoveStringLiteralDfa2_4(active0, 0x400000000000L, active1, 0x4000L);
      case 67:
         return jjMoveStringLiteralDfa2_4(active0, 0L, active1, 0x1000000L);
      case 68:
         if ((active0 & 0x40000L) != 0L)
         {
            jjmatchedKind = 18;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_4(active0, 0L, active1, 0x2001000L);
      case 69:
         return jjMoveStringLiteralDfa2_4(active0, 0xa03208000000L, active1, 0x200400L);
      case 70:
         return jjMoveStringLiteralDfa2_4(active0, 0L, active1, 0x8000L);
      case 71:
         return jjMoveStringLiteralDfa2_4(active0, 0L, active1, 0x80000L);
      case 72:
         if ((active0 & 0x8000000000000000L) != 0L)
         {
            jjmatchedKind = 63;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_4(active0, 0L, active1, 0x120000L);
      case 73:
         if ((active0 & 0x20000000000L) != 0L)
         {
            jjmatchedKind = 41;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_4(active0, 0x102044040004000L, active1, 0L);
      case 76:
         if ((active1 & 0x4L) != 0L)
         {
            jjmatchedKind = 66;
            jjmatchedPos = 1;
         }
         else if ((active1 & 0x10L) != 0L)
         {
            jjmatchedKind = 68;
            jjmatchedPos = 1;
         }
         else if ((active1 & 0x800L) != 0L)
         {
            jjmatchedKind = 75;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_4(active0, 0x100000000000L, active1, 0L);
      case 77:
         if ((active0 & 0x400000000000000L) != 0L)
         {
            jjmatchedKind = 58;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_4(active0, 0x80002000000L, active1, 0L);
      case 78:
         return jjMoveStringLiteralDfa2_4(active0, 0x2000000100000000L, active1, 0L);
      case 79:
         return jjMoveStringLiteralDfa2_4(active0, 0x400000b0008000L, active1, 0x40000L);
      case 80:
         return jjMoveStringLiteralDfa2_4(active0, 0x4000c00000000L, active1, 0x2000L);
      case 82:
         if ((active0 & 0x20000L) != 0L)
         {
            jjmatchedKind = 17;
            jjmatchedPos = 1;
         }
         else if ((active0 & 0x100000L) != 0L)
         {
            jjmatchedKind = 20;
            jjmatchedPos = 1;
         }
         else if ((active0 & 0x1000000000000L) != 0L)
         {
            jjmatchedKind = 48;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_4(active0, 0x1a08000000000000L, active1, 0L);
      case 84:
         if ((active1 & 0x10000L) != 0L)
         {
            jjmatchedKind = 80;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_4(active0, 0x4000000000002000L, active1, 0x400000L);
      case 85:
         return jjMoveStringLiteralDfa2_4(active0, 0x10000000000L, active1, 0x800003L);
      case 97:
         return jjMoveStringLiteralDfa2_4(active0, 0xb0008000010000L, active1, 0x20L);
      case 98:
         return jjMoveStringLiteralDfa2_4(active0, 0x400000000000L, active1, 0x4000L);
      case 99:
         return jjMoveStringLiteralDfa2_4(active0, 0L, active1, 0x1000000L);
      case 100:
         if ((active0 & 0x40000L) != 0L)
         {
            jjmatchedKind = 18;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_4(active0, 0L, active1, 0x2001000L);
      case 101:
         return jjMoveStringLiteralDfa2_4(active0, 0xa03208000000L, active1, 0x200400L);
      case 102:
         return jjMoveStringLiteralDfa2_4(active0, 0L, active1, 0x8000L);
      case 103:
         return jjMoveStringLiteralDfa2_4(active0, 0L, active1, 0x80000L);
      case 104:
         if ((active0 & 0x8000000000000000L) != 0L)
         {
            jjmatchedKind = 63;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_4(active0, 0L, active1, 0x120000L);
      case 105:
         if ((active0 & 0x20000000000L) != 0L)
         {
            jjmatchedKind = 41;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_4(active0, 0x102044040004000L, active1, 0L);
      case 108:
         if ((active1 & 0x4L) != 0L)
         {
            jjmatchedKind = 66;
            jjmatchedPos = 1;
         }
         else if ((active1 & 0x10L) != 0L)
         {
            jjmatchedKind = 68;
            jjmatchedPos = 1;
         }
         else if ((active1 & 0x800L) != 0L)
         {
            jjmatchedKind = 75;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_4(active0, 0x100000000000L, active1, 0L);
      case 109:
         if ((active0 & 0x400000000000000L) != 0L)
         {
            jjmatchedKind = 58;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_4(active0, 0x80002000000L, active1, 0L);
      case 110:
         return jjMoveStringLiteralDfa2_4(active0, 0x2000000100000000L, active1, 0L);
      case 111:
         return jjMoveStringLiteralDfa2_4(active0, 0x400000b0008000L, active1, 0x40000L);
      case 112:
         return jjMoveStringLiteralDfa2_4(active0, 0x4000c00000000L, active1, 0x2000L);
      case 114:
         if ((active0 & 0x20000L) != 0L)
         {
            jjmatchedKind = 17;
            jjmatchedPos = 1;
         }
         else if ((active0 & 0x100000L) != 0L)
         {
            jjmatchedKind = 20;
            jjmatchedPos = 1;
         }
         else if ((active0 & 0x1000000000000L) != 0L)
         {
            jjmatchedKind = 48;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_4(active0, 0x1a08000000000000L, active1, 0L);
      case 116:
         if ((active1 & 0x10000L) != 0L)
         {
            jjmatchedKind = 80;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_4(active0, 0x4000000000002000L, active1, 0x400000L);
      case 117:
         return jjMoveStringLiteralDfa2_4(active0, 0x10000000000L, active1, 0x800003L);
      default :
         break;
   }
   return jjMoveNfa_4(0, 1);
}
private final int jjMoveStringLiteralDfa2_4(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjMoveNfa_4(0, 1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_4(0, 1);
   }
   switch(curChar)
   {
      case 45:
         if ((active1 & 0x1000000000L) != 0L)
         {
            jjmatchedKind = 100;
            jjmatchedPos = 2;
         }
         break;
      case 65:
         return jjMoveStringLiteralDfa3_4(active0, 0x1804280000000000L, active1, 0L);
      case 66:
         if ((active1 & 0x2L) != 0L)
         {
            jjmatchedKind = 65;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_4(active0, 0x8000010000L, active1, 0L);
      case 68:
         return jjMoveStringLiteralDfa3_4(active0, 0x8000L, active1, 0x1000L);
      case 69:
         if ((active0 & 0x200000000000000L) != 0L)
         {
            jjmatchedKind = 57;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_4(active0, 0x8004000000000L, active1, 0x100000L);
      case 71:
         if ((active0 & 0x2000000L) != 0L)
         {
            jjmatchedKind = 25;
            jjmatchedPos = 2;
         }
         else if ((active0 & 0x40000000000L) != 0L)
         {
            jjmatchedKind = 42;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_4(active0, 0x2000000000L, active1, 0L);
      case 74:
         return jjMoveStringLiteralDfa3_4(active0, 0L, active1, 0x4000L);
      case 76:
         if ((active0 & 0x40000000000000L) != 0L)
         {
            jjmatchedKind = 54;
            jjmatchedPos = 2;
         }
         else if ((active1 & 0x400L) != 0L)
         {
            jjmatchedKind = 74;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_4(active0, 0x200000000L, active1, 0x240000L);
      case 77:
         return jjMoveStringLiteralDfa3_4(active0, 0x2000L, active1, 0L);
      case 78:
         if ((active1 & 0x400000L) != 0L)
         {
            jjmatchedKind = 86;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_4(active0, 0x2800020000000L, active1, 0L);
      case 79:
         return jjMoveStringLiteralDfa3_4(active0, 0x500000000000L, active1, 0x2008000L);
      case 80:
         if ((active1 & 0x1L) != 0L)
         {
            jjmatchedKind = 64;
            jjmatchedPos = 2;
         }
         else if ((active1 & 0x20L) != 0L)
         {
            jjmatchedKind = 69;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_4(active0, 0x80000100000000L, active1, 0x2000L);
      case 82:
         return jjMoveStringLiteralDfa3_4(active0, 0x20000080000000L, active1, 0x1020000L);
      case 83:
         if ((active0 & 0x2000000000000000L) != 0L)
         {
            jjmatchedKind = 61;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_4(active0, 0x10000010000000L, active1, 0x80000L);
      case 84:
         return jjMoveStringLiteralDfa3_4(active0, 0x100010c08004000L, active1, 0x800000L);
      case 86:
         if ((active0 & 0x40000000L) != 0L)
         {
            jjmatchedKind = 30;
            jjmatchedPos = 2;
         }
         break;
      case 88:
         return jjMoveStringLiteralDfa3_4(active0, 0x1000000000L, active1, 0L);
      case 89:
         return jjMoveStringLiteralDfa3_4(active0, 0x4000000000000000L, active1, 0L);
      case 97:
         return jjMoveStringLiteralDfa3_4(active0, 0x1804280000000000L, active1, 0L);
      case 98:
         if ((active1 & 0x2L) != 0L)
         {
            jjmatchedKind = 65;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_4(active0, 0x8000010000L, active1, 0L);
      case 100:
         return jjMoveStringLiteralDfa3_4(active0, 0x8000L, active1, 0x1000L);
      case 101:
         if ((active0 & 0x200000000000000L) != 0L)
         {
            jjmatchedKind = 57;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_4(active0, 0x8004000000000L, active1, 0x100000L);
      case 103:
         if ((active0 & 0x2000000L) != 0L)
         {
            jjmatchedKind = 25;
            jjmatchedPos = 2;
         }
         else if ((active0 & 0x40000000000L) != 0L)
         {
            jjmatchedKind = 42;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_4(active0, 0x2000000000L, active1, 0L);
      case 106:
         return jjMoveStringLiteralDfa3_4(active0, 0L, active1, 0x4000L);
      case 108:
         if ((active0 & 0x40000000000000L) != 0L)
         {
            jjmatchedKind = 54;
            jjmatchedPos = 2;
         }
         else if ((active1 & 0x400L) != 0L)
         {
            jjmatchedKind = 74;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_4(active0, 0x200000000L, active1, 0x240000L);
      case 109:
         return jjMoveStringLiteralDfa3_4(active0, 0x2000L, active1, 0L);
      case 110:
         if ((active1 & 0x400000L) != 0L)
         {
            jjmatchedKind = 86;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_4(active0, 0x2800020000000L, active1, 0L);
      case 111:
         return jjMoveStringLiteralDfa3_4(active0, 0x500000000000L, active1, 0x2008000L);
      case 112:
         if ((active1 & 0x1L) != 0L)
         {
            jjmatchedKind = 64;
            jjmatchedPos = 2;
         }
         else if ((active1 & 0x20L) != 0L)
         {
            jjmatchedKind = 69;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_4(active0, 0x80000100000000L, active1, 0x2000L);
      case 114:
         return jjMoveStringLiteralDfa3_4(active0, 0x20000080000000L, active1, 0x1020000L);
      case 115:
         if ((active0 & 0x2000000000000000L) != 0L)
         {
            jjmatchedKind = 61;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_4(active0, 0x10000010000000L, active1, 0x80000L);
      case 116:
         return jjMoveStringLiteralDfa3_4(active0, 0x100010c08004000L, active1, 0x800000L);
      case 118:
         if ((active0 & 0x40000000L) != 0L)
         {
            jjmatchedKind = 30;
            jjmatchedPos = 2;
         }
         break;
      case 120:
         return jjMoveStringLiteralDfa3_4(active0, 0x1000000000L, active1, 0L);
      case 121:
         return jjMoveStringLiteralDfa3_4(active0, 0x4000000000000000L, active1, 0L);
      default :
         break;
   }
   return jjMoveNfa_4(0, 2);
}
private final int jjMoveStringLiteralDfa3_4(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjMoveNfa_4(0, 2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_4(0, 2);
   }
   switch(curChar)
   {
      case 65:
         if ((active0 & 0x8000000L) != 0L)
         {
            jjmatchedKind = 27;
            jjmatchedPos = 3;
         }
         else if ((active0 & 0x8000000000000L) != 0L)
         {
            jjmatchedKind = 51;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_4(active0, 0x20000000000000L, active1, 0L);
      case 67:
         return jjMoveStringLiteralDfa4_4(active0, 0x100010000000L, active1, 0x2100000L);
      case 68:
         if ((active0 & 0x200000000000L) != 0L)
         {
            jjmatchedKind = 45;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_4(active0, 0x400000000000L, active1, 0L);
      case 69:
         if ((active0 & 0x10000000000000L) != 0L)
         {
            jjmatchedKind = 52;
            jjmatchedPos = 3;
         }
         else if ((active0 & 0x100000000000000L) != 0L)
         {
            jjmatchedKind = 56;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_4(active0, 0xa200000000L, active1, 0x224000L);
      case 71:
         return jjMoveStringLiteralDfa4_4(active0, 0x400000000L, active1, 0x40000L);
      case 73:
         return jjMoveStringLiteralDfa4_4(active0, 0x800000000L, active1, 0x1000000L);
      case 75:
         if ((active0 & 0x2000000000000L) != 0L)
         {
            jjmatchedKind = 49;
            jjmatchedPos = 3;
         }
         break;
      case 76:
         if ((active0 & 0x2000L) != 0L)
         {
            jjmatchedKind = 13;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_4(active0, 0x4000084000014000L, active1, 0x2000L);
      case 77:
         if ((active0 & 0x80000000L) != 0L)
         {
            jjmatchedKind = 31;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_4(active0, 0x1800000000000000L, active1, 0L);
      case 78:
         if ((active0 & 0x4000000000000L) != 0L)
         {
            jjmatchedKind = 50;
            jjmatchedPos = 3;
         }
         break;
      case 79:
         return jjMoveStringLiteralDfa4_4(active0, 0L, active1, 0x888000L);
      case 82:
         return jjMoveStringLiteralDfa4_4(active0, 0L, active1, 0x1000L);
      case 84:
         if ((active0 & 0x20000000L) != 0L)
         {
            jjmatchedKind = 29;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_4(active0, 0x80811000000000L, active1, 0L);
      case 85:
         return jjMoveStringLiteralDfa4_4(active0, 0x100000000L, active1, 0L);
      case 89:
         if ((active0 & 0x8000L) != 0L)
         {
            jjmatchedKind = 15;
            jjmatchedPos = 3;
         }
         break;
      case 97:
         if ((active0 & 0x8000000L) != 0L)
         {
            jjmatchedKind = 27;
            jjmatchedPos = 3;
         }
         else if ((active0 & 0x8000000000000L) != 0L)
         {
            jjmatchedKind = 51;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_4(active0, 0x20000000000000L, active1, 0L);
      case 99:
         return jjMoveStringLiteralDfa4_4(active0, 0x100010000000L, active1, 0x2100000L);
      case 100:
         if ((active0 & 0x200000000000L) != 0L)
         {
            jjmatchedKind = 45;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_4(active0, 0x400000000000L, active1, 0L);
      case 101:
         if ((active0 & 0x10000000000000L) != 0L)
         {
            jjmatchedKind = 52;
            jjmatchedPos = 3;
         }
         else if ((active0 & 0x100000000000000L) != 0L)
         {
            jjmatchedKind = 56;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_4(active0, 0xa200000000L, active1, 0x224000L);
      case 103:
         return jjMoveStringLiteralDfa4_4(active0, 0x400000000L, active1, 0x40000L);
      case 105:
         return jjMoveStringLiteralDfa4_4(active0, 0x800000000L, active1, 0x1000000L);
      case 107:
         if ((active0 & 0x2000000000000L) != 0L)
         {
            jjmatchedKind = 49;
            jjmatchedPos = 3;
         }
         break;
      case 108:
         if ((active0 & 0x2000L) != 0L)
         {
            jjmatchedKind = 13;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_4(active0, 0x4000084000014000L, active1, 0x2000L);
      case 109:
         if ((active0 & 0x80000000L) != 0L)
         {
            jjmatchedKind = 31;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_4(active0, 0x1800000000000000L, active1, 0L);
      case 110:
         if ((active0 & 0x4000000000000L) != 0L)
         {
            jjmatchedKind = 50;
            jjmatchedPos = 3;
         }
         break;
      case 111:
         return jjMoveStringLiteralDfa4_4(active0, 0L, active1, 0x888000L);
      case 114:
         return jjMoveStringLiteralDfa4_4(active0, 0L, active1, 0x1000L);
      case 116:
         if ((active0 & 0x20000000L) != 0L)
         {
            jjmatchedKind = 29;
            jjmatchedPos = 3;
         }
         return jjMoveStringLiteralDfa4_4(active0, 0x80811000000000L, active1, 0L);
      case 117:
         return jjMoveStringLiteralDfa4_4(active0, 0x100000000L, active1, 0L);
      case 121:
         if ((active0 & 0x8000L) != 0L)
         {
            jjmatchedKind = 15;
            jjmatchedPos = 3;
         }
         break;
      default :
         break;
   }
   return jjMoveNfa_4(0, 3);
}
private final int jjMoveStringLiteralDfa4_4(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjMoveNfa_4(0, 3);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_4(0, 3);
   }
   switch(curChar)
   {
      case 65:
         return jjMoveStringLiteralDfa5_4(active0, 0x1000000000L, active1, 0x20000L);
      case 67:
         return jjMoveStringLiteralDfa5_4(active0, 0x200000000L, active1, 0x204000L);
      case 68:
         return jjMoveStringLiteralDfa5_4(active0, 0x4000000000L, active1, 0L);
      case 69:
         if ((active0 & 0x4000L) != 0L)
         {
            jjmatchedKind = 14;
            jjmatchedPos = 4;
         }
         else if ((active0 & 0x10000L) != 0L)
         {
            jjmatchedKind = 16;
            jjmatchedPos = 4;
         }
         else if ((active0 & 0x800000000000000L) != 0L)
         {
            jjmatchedKind = 59;
            jjmatchedPos = 4;
         }
         else if ((active0 & 0x4000000000000000L) != 0L)
         {
            jjmatchedKind = 62;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_4(active0, 0x1000800000000000L, active1, 0x3000L);
      case 70:
         return jjMoveStringLiteralDfa5_4(active0, 0L, active1, 0x800000L);
      case 73:
         return jjMoveStringLiteralDfa5_4(active0, 0x80000000000000L, active1, 0L);
      case 75:
         return jjMoveStringLiteralDfa5_4(active0, 0x100000000000L, active1, 0x100000L);
      case 76:
         if ((active0 & 0x8000000000L) != 0L)
         {
            jjmatchedKind = 39;
            jjmatchedPos = 4;
         }
         else if ((active0 & 0x80000000000L) != 0L)
         {
            jjmatchedKind = 43;
            jjmatchedPos = 4;
         }
         break;
      case 77:
         if ((active0 & 0x20000000000000L) != 0L)
         {
            jjmatchedKind = 53;
            jjmatchedPos = 4;
         }
         break;
      case 78:
         return jjMoveStringLiteralDfa5_4(active0, 0x2000000000L, active1, 0L);
      case 79:
         return jjMoveStringLiteralDfa5_4(active0, 0x10800000000L, active1, 0L);
      case 80:
         return jjMoveStringLiteralDfa5_4(active0, 0L, active1, 0x1000000L);
      case 82:
         return jjMoveStringLiteralDfa5_4(active0, 0x410000000L, active1, 0x40000L);
      case 84:
         if ((active0 & 0x100000000L) != 0L)
         {
            jjmatchedKind = 32;
            jjmatchedPos = 4;
         }
         else if ((active1 & 0x8000L) != 0L)
         {
            jjmatchedKind = 79;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_4(active0, 0L, active1, 0x2000000L);
      case 85:
         return jjMoveStringLiteralDfa5_4(active0, 0L, active1, 0x80000L);
      case 89:
         if ((active0 & 0x400000000000L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 4;
         }
         break;
      case 97:
         return jjMoveStringLiteralDfa5_4(active0, 0x1000000000L, active1, 0x20000L);
      case 99:
         return jjMoveStringLiteralDfa5_4(active0, 0x200000000L, active1, 0x204000L);
      case 100:
         return jjMoveStringLiteralDfa5_4(active0, 0x4000000000L, active1, 0L);
      case 101:
         if ((active0 & 0x4000L) != 0L)
         {
            jjmatchedKind = 14;
            jjmatchedPos = 4;
         }
         else if ((active0 & 0x10000L) != 0L)
         {
            jjmatchedKind = 16;
            jjmatchedPos = 4;
         }
         else if ((active0 & 0x800000000000000L) != 0L)
         {
            jjmatchedKind = 59;
            jjmatchedPos = 4;
         }
         else if ((active0 & 0x4000000000000000L) != 0L)
         {
            jjmatchedKind = 62;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_4(active0, 0x1000800000000000L, active1, 0x3000L);
      case 102:
         return jjMoveStringLiteralDfa5_4(active0, 0L, active1, 0x800000L);
      case 105:
         return jjMoveStringLiteralDfa5_4(active0, 0x80000000000000L, active1, 0L);
      case 107:
         return jjMoveStringLiteralDfa5_4(active0, 0x100000000000L, active1, 0x100000L);
      case 108:
         if ((active0 & 0x8000000000L) != 0L)
         {
            jjmatchedKind = 39;
            jjmatchedPos = 4;
         }
         else if ((active0 & 0x80000000000L) != 0L)
         {
            jjmatchedKind = 43;
            jjmatchedPos = 4;
         }
         break;
      case 109:
         if ((active0 & 0x20000000000000L) != 0L)
         {
            jjmatchedKind = 53;
            jjmatchedPos = 4;
         }
         break;
      case 110:
         return jjMoveStringLiteralDfa5_4(active0, 0x2000000000L, active1, 0L);
      case 111:
         return jjMoveStringLiteralDfa5_4(active0, 0x10800000000L, active1, 0L);
      case 112:
         return jjMoveStringLiteralDfa5_4(active0, 0L, active1, 0x1000000L);
      case 114:
         return jjMoveStringLiteralDfa5_4(active0, 0x410000000L, active1, 0x40000L);
      case 116:
         if ((active0 & 0x100000000L) != 0L)
         {
            jjmatchedKind = 32;
            jjmatchedPos = 4;
         }
         else if ((active1 & 0x8000L) != 0L)
         {
            jjmatchedKind = 79;
            jjmatchedPos = 4;
         }
         return jjMoveStringLiteralDfa5_4(active0, 0L, active1, 0x2000000L);
      case 117:
         return jjMoveStringLiteralDfa5_4(active0, 0L, active1, 0x80000L);
      case 121:
         if ((active0 & 0x400000000000L) != 0L)
         {
            jjmatchedKind = 46;
            jjmatchedPos = 4;
         }
         break;
      default :
         break;
   }
   return jjMoveNfa_4(0, 4);
}
private final int jjMoveStringLiteralDfa5_4(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjMoveNfa_4(0, 4);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_4(0, 4);
   }
   switch(curChar)
   {
      case 68:
         if ((active0 & 0x2000000000L) != 0L)
         {
            jjmatchedKind = 37;
            jjmatchedPos = 5;
         }
         else if ((active1 & 0x20000L) != 0L)
         {
            jjmatchedKind = 81;
            jjmatchedPos = 5;
         }
         break;
      case 69:
         return jjMoveStringLiteralDfa6_4(active0, 0L, active1, 0x100000L);
      case 73:
         return jjMoveStringLiteralDfa6_4(active0, 0x10000000L, active1, 0L);
      case 78:
         if ((active0 & 0x800000000L) != 0L)
         {
            jjmatchedKind = 35;
            jjmatchedPos = 5;
         }
         else if ((active0 & 0x10000000000L) != 0L)
         {
            jjmatchedKind = 40;
            jjmatchedPos = 5;
         }
         return jjMoveStringLiteralDfa6_4(active0, 0L, active1, 0x80000L);
      case 79:
         return jjMoveStringLiteralDfa6_4(active0, 0x80000400000000L, active1, 0x840000L);
      case 81:
         return jjMoveStringLiteralDfa6_4(active0, 0x100000000000L, active1, 0L);
      case 82:
         if ((active0 & 0x800000000000L) != 0L)
         {
            jjmatchedKind = 47;
            jjmatchedPos = 5;
         }
         return jjMoveStringLiteralDfa6_4(active0, 0x1000000000L, active1, 0L);
      case 83:
         return jjMoveStringLiteralDfa6_4(active0, 0x1000004000000000L, active1, 0x1000L);
      case 84:
         if ((active0 & 0x200000000L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 5;
         }
         else if ((active1 & 0x2000L) != 0L)
         {
            jjmatchedKind = 77;
            jjmatchedPos = 5;
         }
         else if ((active1 & 0x4000L) != 0L)
         {
            jjmatchedKind = 78;
            jjmatchedPos = 5;
         }
         else if ((active1 & 0x1000000L) != 0L)
         {
            jjmatchedKind = 88;
            jjmatchedPos = 5;
         }
         return jjMoveStringLiteralDfa6_4(active0, 0L, active1, 0x200000L);
      case 89:
         return jjMoveStringLiteralDfa6_4(active0, 0L, active1, 0x2000000L);
      case 100:
         if ((active0 & 0x2000000000L) != 0L)
         {
            jjmatchedKind = 37;
            jjmatchedPos = 5;
         }
         else if ((active1 & 0x20000L) != 0L)
         {
            jjmatchedKind = 81;
            jjmatchedPos = 5;
         }
         break;
      case 101:
         return jjMoveStringLiteralDfa6_4(active0, 0L, active1, 0x100000L);
      case 105:
         return jjMoveStringLiteralDfa6_4(active0, 0x10000000L, active1, 0L);
      case 110:
         if ((active0 & 0x800000000L) != 0L)
         {
            jjmatchedKind = 35;
            jjmatchedPos = 5;
         }
         else if ((active0 & 0x10000000000L) != 0L)
         {
            jjmatchedKind = 40;
            jjmatchedPos = 5;
         }
         return jjMoveStringLiteralDfa6_4(active0, 0L, active1, 0x80000L);
      case 111:
         return jjMoveStringLiteralDfa6_4(active0, 0x80000400000000L, active1, 0x840000L);
      case 113:
         return jjMoveStringLiteralDfa6_4(active0, 0x100000000000L, active1, 0L);
      case 114:
         if ((active0 & 0x800000000000L) != 0L)
         {
            jjmatchedKind = 47;
            jjmatchedPos = 5;
         }
         return jjMoveStringLiteralDfa6_4(active0, 0x1000000000L, active1, 0L);
      case 115:
         return jjMoveStringLiteralDfa6_4(active0, 0x1000004000000000L, active1, 0x1000L);
      case 116:
         if ((active0 & 0x200000000L) != 0L)
         {
            jjmatchedKind = 33;
            jjmatchedPos = 5;
         }
         else if ((active1 & 0x2000L) != 0L)
         {
            jjmatchedKind = 77;
            jjmatchedPos = 5;
         }
         else if ((active1 & 0x4000L) != 0L)
         {
            jjmatchedKind = 78;
            jjmatchedPos = 5;
         }
         else if ((active1 & 0x1000000L) != 0L)
         {
            jjmatchedKind = 88;
            jjmatchedPos = 5;
         }
         return jjMoveStringLiteralDfa6_4(active0, 0L, active1, 0x200000L);
      case 121:
         return jjMoveStringLiteralDfa6_4(active0, 0L, active1, 0x2000000L);
      default :
         break;
   }
   return jjMoveNfa_4(0, 5);
}
private final int jjMoveStringLiteralDfa6_4(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjMoveNfa_4(0, 5);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_4(0, 5);
   }
   switch(curChar)
   {
      case 67:
         return jjMoveStringLiteralDfa7_4(active0, 0L, active1, 0x800000L);
      case 68:
         if ((active1 & 0x80000L) != 0L)
         {
            jjmatchedKind = 83;
            jjmatchedPos = 6;
         }
         else if ((active1 & 0x100000L) != 0L)
         {
            jjmatchedKind = 84;
            jjmatchedPos = 6;
         }
         break;
      case 69:
         return jjMoveStringLiteralDfa7_4(active0, 0x1000005000000000L, active1, 0x200000L);
      case 78:
         if ((active0 & 0x80000000000000L) != 0L)
         {
            jjmatchedKind = 55;
            jjmatchedPos = 6;
         }
         break;
      case 80:
         return jjMoveStringLiteralDfa7_4(active0, 0x10000000L, active1, 0x2000000L);
      case 83:
         if ((active1 & 0x1000L) != 0L)
         {
            jjmatchedKind = 76;
            jjmatchedPos = 6;
         }
         break;
      case 85:
         return jjMoveStringLiteralDfa7_4(active0, 0x100400000000L, active1, 0x40000L);
      case 99:
         return jjMoveStringLiteralDfa7_4(active0, 0L, active1, 0x800000L);
      case 100:
         if ((active1 & 0x80000L) != 0L)
         {
            jjmatchedKind = 83;
            jjmatchedPos = 6;
         }
         else if ((active1 & 0x100000L) != 0L)
         {
            jjmatchedKind = 84;
            jjmatchedPos = 6;
         }
         break;
      case 101:
         return jjMoveStringLiteralDfa7_4(active0, 0x1000005000000000L, active1, 0x200000L);
      case 110:
         if ((active0 & 0x80000000000000L) != 0L)
         {
            jjmatchedKind = 55;
            jjmatchedPos = 6;
         }
         break;
      case 112:
         return jjMoveStringLiteralDfa7_4(active0, 0x10000000L, active1, 0x2000000L);
      case 115:
         if ((active1 & 0x1000L) != 0L)
         {
            jjmatchedKind = 76;
            jjmatchedPos = 6;
         }
         break;
      case 117:
         return jjMoveStringLiteralDfa7_4(active0, 0x100400000000L, active1, 0x40000L);
      default :
         break;
   }
   return jjMoveNfa_4(0, 6);
}
private final int jjMoveStringLiteralDfa7_4(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjMoveNfa_4(0, 6);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_4(0, 6);
   }
   switch(curChar)
   {
      case 65:
         if ((active0 & 0x1000000000L) != 0L)
         {
            jjmatchedKind = 36;
            jjmatchedPos = 7;
         }
         break;
      case 68:
         if ((active1 & 0x200000L) != 0L)
         {
            jjmatchedKind = 85;
            jjmatchedPos = 7;
         }
         break;
      case 69:
         if ((active1 & 0x2000000L) != 0L)
         {
            jjmatchedKind = 89;
            jjmatchedPos = 7;
         }
         break;
      case 79:
         return jjMoveStringLiteralDfa8_4(active0, 0x100000000000L, active1, 0L);
      case 80:
         if ((active0 & 0x400000000L) != 0L)
         {
            jjmatchedKind = 34;
            jjmatchedPos = 7;
         }
         else if ((active1 & 0x40000L) != 0L)
         {
            jjmatchedKind = 82;
            jjmatchedPos = 7;
         }
         break;
      case 84:
         if ((active0 & 0x10000000L) != 0L)
         {
            jjmatchedKind = 28;
            jjmatchedPos = 7;
         }
         else if ((active0 & 0x4000000000L) != 0L)
         {
            jjmatchedKind = 38;
            jjmatchedPos = 7;
         }
         else if ((active0 & 0x1000000000000000L) != 0L)
         {
            jjmatchedKind = 60;
            jjmatchedPos = 7;
         }
         break;
      case 85:
         return jjMoveStringLiteralDfa8_4(active0, 0L, active1, 0x800000L);
      case 97:
         if ((active0 & 0x1000000000L) != 0L)
         {
            jjmatchedKind = 36;
            jjmatchedPos = 7;
         }
         break;
      case 100:
         if ((active1 & 0x200000L) != 0L)
         {
            jjmatchedKind = 85;
            jjmatchedPos = 7;
         }
         break;
      case 101:
         if ((active1 & 0x2000000L) != 0L)
         {
            jjmatchedKind = 89;
            jjmatchedPos = 7;
         }
         break;
      case 111:
         return jjMoveStringLiteralDfa8_4(active0, 0x100000000000L, active1, 0L);
      case 112:
         if ((active0 & 0x400000000L) != 0L)
         {
            jjmatchedKind = 34;
            jjmatchedPos = 7;
         }
         else if ((active1 & 0x40000L) != 0L)
         {
            jjmatchedKind = 82;
            jjmatchedPos = 7;
         }
         break;
      case 116:
         if ((active0 & 0x10000000L) != 0L)
         {
            jjmatchedKind = 28;
            jjmatchedPos = 7;
         }
         else if ((active0 & 0x4000000000L) != 0L)
         {
            jjmatchedKind = 38;
            jjmatchedPos = 7;
         }
         else if ((active0 & 0x1000000000000000L) != 0L)
         {
            jjmatchedKind = 60;
            jjmatchedPos = 7;
         }
         break;
      case 117:
         return jjMoveStringLiteralDfa8_4(active0, 0L, active1, 0x800000L);
      default :
         break;
   }
   return jjMoveNfa_4(0, 7);
}
private final int jjMoveStringLiteralDfa8_4(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjMoveNfa_4(0, 7);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_4(0, 7);
   }
   switch(curChar)
   {
      case 83:
         if ((active1 & 0x800000L) != 0L)
         {
            jjmatchedKind = 87;
            jjmatchedPos = 8;
         }
         break;
      case 84:
         return jjMoveStringLiteralDfa9_4(active0, 0x100000000000L, active1, 0L);
      case 115:
         if ((active1 & 0x800000L) != 0L)
         {
            jjmatchedKind = 87;
            jjmatchedPos = 8;
         }
         break;
      case 116:
         return jjMoveStringLiteralDfa9_4(active0, 0x100000000000L, active1, 0L);
      default :
         break;
   }
   return jjMoveNfa_4(0, 8);
}
private final int jjMoveStringLiteralDfa9_4(long old0, long active0, long old1, long active1)
{
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjMoveNfa_4(0, 8);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
   return jjMoveNfa_4(0, 8);
   }
   switch(curChar)
   {
      case 69:
         if ((active0 & 0x100000000000L) != 0L)
         {
            jjmatchedKind = 44;
            jjmatchedPos = 9;
         }
         break;
      case 101:
         if ((active0 & 0x100000000000L) != 0L)
         {
            jjmatchedKind = 44;
            jjmatchedPos = 9;
         }
         break;
      default :
         break;
   }
   return jjMoveNfa_4(0, 9);
}
private final void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private final void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}
@SuppressWarnings("unused")
private final int jjMoveNfa_4(int startState, int curPos)
{
   int strKind = jjmatchedKind;
   int strPos = jjmatchedPos;
   int seenUpto;
   input_stream.backup(seenUpto = curPos + 1);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { throw new Error("Internal Error"); }
   curPos = 0;
   int startsAt = 0;
   jjnewStateCnt = 3;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if ((0x3ff200000000000L & l) == 0L)
                     break;
                  if (kind > 92)
                     kind = 92;
                  jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 2:
                  if ((0x3ff200000000000L & l) == 0L)
                     break;
                  if (kind > 94)
                     kind = 94;
                  jjstateSet[jjnewStateCnt++] = 2;
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               case 0:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 92)
                     kind = 92;
                  jjCheckNAddTwoStates(1, 2);
                  break;
               case 1:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 92)
                     kind = 92;
                  jjCheckNAdd(1);
                  break;
               case 2:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 94)
                     kind = 94;
                  jjCheckNAdd(2);
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
    	 MatchLoop: do
         {
            switch(jjstateSet[--i])
            {
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 3 - (jjnewStateCnt = startsAt)))
         break;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { break; }
   }
   if (jjmatchedPos > strPos)
      return curPos;

   int toRet = Math.max(curPos, seenUpto);

   if (curPos < toRet)
      for (i = toRet - Math.min(curPos, seenUpto); i-- > 0; )
         try { curChar = input_stream.readChar(); }
         catch(java.io.IOException e) { throw new Error("Internal Error : Please send a bug report."); }

   if (jjmatchedPos < strPos)
   {
      jjmatchedKind = strKind;
      jjmatchedPos = strPos;
   }
   else if (jjmatchedPos == strPos && jjmatchedKind > strKind)
      jjmatchedKind = strKind;

   return toRet;
}
private final int jjMoveStringLiteralDfa0_3()
{
   switch(curChar)
   {
      case 45:
         return jjMoveStringLiteralDfa1_3(0x2000000000L);
      default :
         return 1;
   }
}
private final int jjMoveStringLiteralDfa1_3(long active1)
{
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      return 1;
   }
   switch(curChar)
   {
      case 45:
         return jjMoveStringLiteralDfa2_3(active1, 0x2000000000L);
      default :
         return 2;
   }
}
private final int jjMoveStringLiteralDfa2_3(long old1, long active1)
{
   if (((active1 &= old1)) == 0L)
      return 2;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      return 2;
   }
   switch(curChar)
   {
      case 62:
         if ((active1 & 0x2000000000L) != 0L)
            return jjStopAtPos(2, 101);
         break;
      default :
         return 3;
   }
   return 3;
}
static final int[] jjnextStates = {
};
public static final String[] jjstrLiteralImages = {
null, null, null, null, null, null, "\74", "\74\57", null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, "\75", "\72", null, null, null, 
"\77", "\76", "\57\76", null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, };
public static final String[] lexStateNames = {
   "BODY_STR", 
   "SQ_STR", 
   "DQ_STR", 
   "COMM", 
   "IN_TAG", 
   "DEFAULT", 
};
public static final int[] jjnewLexState = {
   -1, -1, -1, -1, -1, -1, 4, 4, 0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 5, 5, 2, 1, 
   3, 5, -1, 4, -1, -1, 4, -1, -1, 4, 4, -1, -1, 
};
static final long[] jjtoToken = {
   0xffffffffffffe0c1L, 0xe4a3dfffffffL, 
};
static final long[] jjtoSkip = {
   0x1e00L, 0x0L, 
};
static final long[] jjtoMore = {
   0x100L, 0x11b5c00000000L, 
};
protected SimpleCharStream input_stream;
private final int[] jjrounds = new int[3];
private final int[] jjstateSet = new int[6];
StringBuffer image;
int jjimageLen;
int lengthOfMatch;
protected char curChar;
public AlinousObjectParserTokenManager(SimpleCharStream stream){
   if (SimpleCharStream.staticFlag)
      throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
   input_stream = stream;
}
public AlinousObjectParserTokenManager(SimpleCharStream stream, int lexState){
   this(stream);
   SwitchTo(lexState);
}
public void ReInit(SimpleCharStream stream)
{
   jjmatchedPos = jjnewStateCnt = 0;
   curLexState = defaultLexState;
   input_stream = stream;
   ReInitRounds();
}
private final void ReInitRounds()
{
   int i;
   jjround = 0x80000001;
   for (i = 3; i-- > 0;)
      jjrounds[i] = 0x80000000;
}
public void ReInit(SimpleCharStream stream, int lexState)
{
   ReInit(stream);
   SwitchTo(lexState);
}
public void SwitchTo(int lexState)
{
   if (lexState >= 6 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
   else
      curLexState = lexState;
}

protected Token jjFillToken()
{
   Token t = Token.newToken(jjmatchedKind);
   t.kind = jjmatchedKind;
   String im = jjstrLiteralImages[jjmatchedKind];
   t.image = (im == null) ? input_stream.GetImage() : im;
   t.beginLine = input_stream.getBeginLine();
   t.beginColumn = input_stream.getBeginColumn();
   t.endLine = input_stream.getEndLine();
   t.endColumn = input_stream.getEndColumn();
   return t;
}

int curLexState = 5;
int defaultLexState = 5;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {   
   try   
   {     
      curChar = input_stream.BeginToken();
   }     
   catch(java.io.IOException e)
   {        
      jjmatchedKind = 0;
      matchedToken = jjFillToken();
      return matchedToken;
   }
   image = null;
   jjimageLen = 0;

   for (;;)
   {
     switch(curLexState)
     {
       case 0:
         jjmatchedKind = 0x7fffffff;
         jjmatchedPos = 0;
         curPos = jjMoveStringLiteralDfa0_0();
         if (jjmatchedPos == 0 && jjmatchedKind > 112)
         {
            jjmatchedKind = 112;
         }
         break;
       case 1:
         jjmatchedKind = 0x7fffffff;
         jjmatchedPos = 0;
         curPos = jjMoveStringLiteralDfa0_1();
         if (jjmatchedPos == 0 && jjmatchedKind > 108)
         {
            jjmatchedKind = 108;
         }
         break;
       case 2:
         jjmatchedKind = 0x7fffffff;
         jjmatchedPos = 0;
         curPos = jjMoveStringLiteralDfa0_2();
         if (jjmatchedPos == 0 && jjmatchedKind > 105)
         {
            jjmatchedKind = 105;
         }
         break;
       case 3:
         jjmatchedKind = 0x7fffffff;
         jjmatchedPos = 0;
         curPos = jjMoveStringLiteralDfa0_3();
         if (jjmatchedPos == 0 && jjmatchedKind > 102)
         {
            jjmatchedKind = 102;
         }
         break;
       case 4:
         jjmatchedKind = 0x7fffffff;
         jjmatchedPos = 0;
         curPos = jjMoveStringLiteralDfa0_4();
         break;
       case 5:
         jjmatchedKind = 0x7fffffff;
         jjmatchedPos = 0;
         curPos = jjMoveStringLiteralDfa0_5();
         if (jjmatchedPos == 0 && jjmatchedKind > 8)
         {
            jjmatchedKind = 8;
         }
         break;
     }
     if (jjmatchedKind != 0x7fffffff)
     {
        if (jjmatchedPos + 1 < curPos)
           input_stream.backup(curPos - jjmatchedPos - 1);
        if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
        {
           matchedToken = jjFillToken();
           TokenLexicalActions(matchedToken);
       if (jjnewLexState[jjmatchedKind] != -1)
         curLexState = jjnewLexState[jjmatchedKind];
           return matchedToken;
        }
        else if ((jjtoSkip[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
        {
         if (jjnewLexState[jjmatchedKind] != -1)
           curLexState = jjnewLexState[jjmatchedKind];
           continue EOFLoop;
        }
        jjimageLen += jjmatchedPos + 1;
      if (jjnewLexState[jjmatchedKind] != -1)
        curLexState = jjnewLexState[jjmatchedKind];
        curPos = 0;
        jjmatchedKind = 0x7fffffff;
        try {
           curChar = input_stream.readChar();
           continue;
        }
        catch (java.io.IOException e1) { }
     }
     int error_line = input_stream.getEndLine();
     int error_column = input_stream.getEndColumn();
     String error_after = null;
     boolean EOFSeen = false;
     try { input_stream.readChar(); input_stream.backup(1); }
     catch (java.io.IOException e1) {
        EOFSeen = true;
        error_after = curPos <= 1 ? "" : input_stream.GetImage();
        if (curChar == '\n' || curChar == '\r') {
           error_line++;
           error_column = 0;
        }
        else
           error_column++;
     }
     if (!EOFSeen) {
        input_stream.backup(1);
        error_after = curPos <= 1 ? "" : input_stream.GetImage();
     }
     throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
   }
  }
}

void TokenLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      case 101 :
        if (image == null)
            image = new StringBuffer();
            image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                matchedToken.image = image.substring(3, image.length() - 3);
         break;
      case 103 :
        if (image == null)
            image = new StringBuffer();
            image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                matchedToken.image = image.substring(1, image.length() - 1);
         break;
      case 106 :
        if (image == null)
            image = new StringBuffer();
            image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                matchedToken.image = image.substring(1, image.length() - 1);
         break;
      case 109 :
        if (image == null)
            image = new StringBuffer();
            image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                if(image.length() >= 2 && image.charAt(image.length() - 1) == '<'){
                        matchedToken.image = image.substring(0, image.length() - 1);
                }
         break;
      case 110 :
        if (image == null)
            image = new StringBuffer();
            image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                if(image.length() >= 3 && image.charAt(image.length() - 2) == '<'){
                        matchedToken.image = image.substring(0, image.length() - 2);
                }
         break;
      case 111 :
        if (image == null)
            image = new StringBuffer();
            image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                if(image.length() >= 3 && image.charAt(image.length() - 2) == '<'){
                        matchedToken.image = image.substring(0, image.length() - 2);
                }
         break;
      default : 
         break;
   }
}
}
