/* Generated By:JavaCC: Do not edit this line. AlinousAttrScriptParserConstants.java */
package org.alinous.parser.script.attr;

public interface AlinousAttrScriptParserConstants {

  int EOF = 0;
  int NOTASCII = 1;
  int ASCILETTER = 2;
  int NUMBERLETTER = 3;
  int COLON = 4;
  int SEMI_COLON = 5;
  int CHARACTOR = 6;
  int EOF_DEF = 7;
  int LT_DEFAULT = 8;
  int L_BRACE = 9;
  int GT_DEFAULT = 10;
  int BODY_L_BRACE = 13;
  int GT_BODY = 14;
  int DOLLAR = 22;
  int CMP_EQUALS = 23;
  int CMP_NOTEQUALS = 24;
  int GT = 25;
  int GEQ = 26;
  int LT = 27;
  int LEQ = 28;
  int L_BRACKET = 29;
  int R_BRACKET = 30;
  int L_PARENTHESIS = 31;
  int R_PARENTHESIS = 32;
  int DOT = 33;
  int ASTERISK = 34;
  int PLUSPLUS = 35;
  int PLUS = 36;
  int MINUSMINUS = 37;
  int MINUS = 38;
  int DIV = 39;
  int MODULO = 40;
  int LOGICAL_AND = 41;
  int LOGICAL_OR = 42;
  int COMMA = 43;
  int AT_MARK = 44;
  int NOT = 45;
  int R_BRACE = 46;
  int TRUE = 47;
  int FALSE = 48;
  int BOOL = 49;
  int IF = 50;
  int NULL = 51;
  int IDENTIFIER = 52;
  int NUMERIC = 53;
  int DQSTRLIT = 56;
  int SQSTRLIT = 59;

  int SQ_STR = 0;
  int DQ_STR = 1;
  int SCRIPT = 2;
  int BODY_STR = 3;
  int BASE = 4;
  int DEFAULT = 5;

  String[] tokenImage = {
    "<EOF>",
    "<NOTASCII>",
    "<ASCILETTER>",
    "<NUMBERLETTER>",
    "\":\"",
    "\";\"",
    "<CHARACTOR>",
    "\"\\u0000\"",
    "\"<\"",
    "\"{\"",
    "\">\"",
    "\"\\\\{\"",
    "<token of kind 12>",
    "\"{\"",
    "\">\"",
    "\"\\\\{\"",
    "\"\\\\>\"",
    "<token of kind 17>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"$\"",
    "\"==\"",
    "\"!=\"",
    "\">\"",
    "\">=\"",
    "\"<\"",
    "\"<=\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\".\"",
    "\"*\"",
    "\"++\"",
    "\"+\"",
    "\"--\"",
    "\"-\"",
    "\"/\"",
    "\"%\"",
    "\"&&\"",
    "\"||\"",
    "\",\"",
    "\"@\"",
    "\"!\"",
    "\"}\"",
    "\"TRUE\"",
    "\"FALSE\"",
    "\"BOOL\"",
    "\"IF\"",
    "\"NULL\"",
    "<IDENTIFIER>",
    "<NUMERIC>",
    "\"\\\"\"",
    "\"\\\'\"",
    "\"\\\"\"",
    "\"\\\\\\\"\"",
    "<token of kind 58>",
    "\"\\\'\"",
    "\"\\\\\\\'\"",
    "<token of kind 61>",
  };

}
