/* Generated By:JavaCC: Do not edit this line. AlinousXmlObjectParserConstants.java */
package org.alinous.parser.xml;

public interface AlinousXmlObjectParserConstants {

  int EOF = 0;
  int NOTASCII = 1;
  int ASCILETTER = 2;
  int NUMBERLETTER = 3;
  int CHARACTOR = 4;
  int MINUS = 5;
  int TAG_BEGIN = 6;
  int TAG_END_BEGIN = 7;
  int HTML = 13;
  int BODY = 14;
  int TABLE = 15;
  int TR = 16;
  int TD = 17;
  int B = 18;
  int BR = 19;
  int H1 = 20;
  int H2 = 21;
  int H3 = 22;
  int P = 23;
  int IMG = 24;
  int A = 25;
  int META = 26;
  int SCRIPT = 27;
  int NOSCRIPT = 28;
  int FONT = 29;
  int DIV = 30;
  int FORM = 31;
  int INPUT = 32;
  int SELECT = 33;
  int OPTGROUP = 34;
  int OPTION = 35;
  int TEXTAREA = 36;
  int LEGEND = 37;
  int FIELDSET = 38;
  int LABEL = 39;
  int BUTTON = 40;
  int LI = 41;
  int BIG = 42;
  int SMALL = 43;
  int BLOCKQUOTE = 44;
  int HEAD = 45;
  int TBODY = 46;
  int CENTER = 47;
  int HR = 48;
  int SPAN = 49;
  int AREA = 50;
  int BASE = 51;
  int PARAM = 52;
  int COL = 53;
  int CAPTION = 54;
  int CITE = 55;
  int PRE = 56;
  int EM = 57;
  int FRAME = 58;
  int FRAMESET = 59;
  int INS = 60;
  int STYLE = 61;
  int TH = 62;
  int SUP = 63;
  int SUB = 64;
  int UL = 65;
  int Q = 66;
  int OL = 67;
  int MAP = 68;
  int I = 69;
  int H4 = 70;
  int H5 = 71;
  int H6 = 72;
  int DEL = 73;
  int DL = 74;
  int ADDRESS = 75;
  int APPLET = 76;
  int OBJECT = 77;
  int TFOOT = 78;
  int TT = 79;
  int THREAD = 80;
  int COLGROUP = 81;
  int CHECKED = 82;
  int SELECTED = 83;
  int DOCTYPE = 84;
  int EQUALS = 85;
  int COLON = 86;
  int IDENTIFIER = 87;
  int ATTR_SUB = 88;
  int ATTR_IDENTIFIER = 89;
  int QUESTION = 90;
  int HTML_TAG_END = 91;
  int XML_TAG_END = 92;
  int DQ = 93;
  int SQ = 94;
  int CDATA_BEGIN = 96;
  int CDATA_END = 97;
  int COMMENT = 99;
  int DQ_END = 101;
  int SQ_END = 104;
  int STR2TAG = 107;
  int STR2TAG_END_BEGIN = 108;
  int STR_EOF = 109;

  int BODY_STR = 0;
  int SQ_STR = 1;
  int DQ_STR = 2;
  int COMM = 3;
  int CDATA = 4;
  int IN_TAG = 5;
  int DEFAULT = 6;

  String[] tokenImage = {
    "<EOF>",
    "<NOTASCII>",
    "<ASCILETTER>",
    "<NUMBERLETTER>",
    "<CHARACTOR>",
    "\"-\"",
    "\"<\"",
    "\"</\"",
    "<token of kind 8>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"HTML\"",
    "\"BODY\"",
    "\"TABLE\"",
    "\"TR\"",
    "\"TD\"",
    "\"B\"",
    "\"BR\"",
    "\"H1\"",
    "\"H2\"",
    "\"H3\"",
    "\"P\"",
    "\"IMG\"",
    "\"A\"",
    "\"META\"",
    "\"SCRIPT\"",
    "\"NOSCRIPT\"",
    "\"FONT\"",
    "\"DIV\"",
    "\"FORM\"",
    "\"INPUT\"",
    "\"SELECT\"",
    "\"OPTGROUP\"",
    "\"OPTION\"",
    "\"TEXTAREA\"",
    "\"LEGEND\"",
    "\"FIELDSET\"",
    "\"LABEL\"",
    "\"BUTTON\"",
    "\"LI\"",
    "\"BIG\"",
    "\"SMALL\"",
    "\"BLOCKQUOTE\"",
    "\"HEAD\"",
    "\"TBODY\"",
    "\"CENTER\"",
    "\"HR\"",
    "\"SPAN\"",
    "\"AREA\"",
    "\"BASE\"",
    "\"PARAM\"",
    "\"COL\"",
    "\"CAPTION\"",
    "\"CITE\"",
    "\"PRE\"",
    "\"EM\"",
    "\"FRAME\"",
    "\"FRAMESET\"",
    "\"INS\"",
    "\"STYLE\"",
    "\"TH\"",
    "\"SUP\"",
    "\"SUB\"",
    "\"UL\"",
    "\"Q\"",
    "\"OL\"",
    "\"MAP\"",
    "\"I\"",
    "\"H4\"",
    "\"H5\"",
    "\"H6\"",
    "\"DEL\"",
    "\"DL\"",
    "\"ADDRESS\"",
    "\"APPLET\"",
    "\"OBJECT\"",
    "\"TFOOT\"",
    "\"TT\"",
    "\"THREAD\"",
    "\"COLGROUP\"",
    "\"CHECKED\"",
    "\"SELECTED\"",
    "\"!DOCTYPE\"",
    "\"=\"",
    "\":\"",
    "<IDENTIFIER>",
    "<ATTR_SUB>",
    "<ATTR_IDENTIFIER>",
    "\"?\"",
    "\">\"",
    "\"/>\"",
    "\"\\\"\"",
    "\"\\\'\"",
    "\"!--\"",
    "\"![CDATA[\"",
    "\"]]>\"",
    "<token of kind 98>",
    "\"-->\"",
    "<token of kind 100>",
    "\"\\\"\"",
    "\"\\\\\\\"\"",
    "<token of kind 103>",
    "\"\\\'\"",
    "\"\\\\\\\'\"",
    "<token of kind 106>",
    "\"<\"",
    "\"</\"",
    "\"\\u0000\"",
    "<token of kind 110>",
  };

}
